quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:demodb;DB_CLOSE_DELAY=-1
quarkus.datasource.jdbc.max-size=16

quarkus.flyway.migrate-at-start=true
quarkus.flyway.baseline-on-migrate=true

quarkus.hibernate-orm.database.generation=none

quarkus.http.port=8080

inertia.root-template=index.html
inertia.version-strategy=custom
inertia.version-custom=1.0.0

demo.seed.enabled=true
demo.seed.count=10000
demo.seed.batch-size=500

quarkus.arc.index-dependency.quarkus-inertia=io.github.dg.quarkus.inertia
quarkus.http.test-port=8082
